---
- name: Refresh dnf cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Install RHEL packages
  ansible.builtin.dnf:
    name: "{{ rhel_packages }}"
    state: present
  become: true
