---
flatpak_apps:
  - md.obsidian.Obsidian
  - com.github.tchx84.Flatseal
  - com.discordapp.Discord
  - com.rustdesk.RustDesk
  - com.spotify.Client
  - org.jellyfin.JellyfinDesktop
  - org.signal.Signal
  - com.brave.Browser
